### PR TITLE
Docker builds

### PR DESCRIPTION
**Pull request by palp**
- Add dockerfile for bot
- Add build actions for docker images (bot + backend)

### CODE REVIEW

**Comment by yk** [comment]
do we need to build & publish on every push? Do you think it makes sense to restrict it to tags starting with "v", which would then be our releases?

**Comment by palp** [comment]
> do we need to build & publish on every push? Do you think it makes sense to restrict it to tags starting with "v", which would then be our releases?

Yeah, every push is probably too much. PR builds might be useful for testing, but also probably a lot of noise. I'll set it up to work off tags for now and we can adjust if needed.

**Comment by palp** [comment]
I left in the path filters, which should skip "empty" releases (i.e., only the bot was modified, so no new image is built of the backend). This may or may not make sense to do.

**Review by yk — APPROVED** [review]
thank you!

**Pull request merged**
